export const AmountCode = [
  { code: 'INR', label: 'India' },
  { code: 'NPR', label: 'Nepal' },
  { code: 'USD', label: 'United States' },
]

// export const AmountCode = [
//     { code: 'AFN', label: 'Afghanistan' },
//     { code: 'ALL', label: 'Albania' },
//     { code: 'DZD', label: 'Algeria' },
//     { code: 'EUR', label: 'Andorra' },
//     { code: 'AOA', label: 'Angola' },
//     { code: 'ARS', label: 'Argentina' },
//     { code: 'AMD', label: 'Armenia' },
//     { code: 'AUD', label: 'Australia' },
//     { code: 'EUR', label: 'Austria' },
//     { code: 'AZN', label: 'Azerbaijan' },
//     { code: 'BSD', label: 'Bahamas' },
//     { code: 'BHD', label: 'Bahrain' },
//     { code: 'BDT', label: 'Bangladesh' },
//     { code: 'BBD', label: 'Barbados' },
//     { code: 'BYN', label: 'Belarus' },
//     { code: 'EUR', label: 'Belgium' },
//     { code: 'BZD', label: 'Belize' },
//     { code: 'XOF', label: 'Benin' },
//     { code: 'BTN', label: 'Bhutan' },
//     { code: 'BOB', label: 'Bolivia' },
//     { code: 'BAM', label: 'Bosnia and Herzegovina' },
//     { code: 'BWP', label: 'Botswana' },
//     { code: 'BRL', label: 'Brazil' },
//     { code: 'BND', label: 'Brunei' },
//     { code: 'BGN', label: 'Bulgaria' },
//     { code: 'XOF', label: 'Burkina Faso' },
//     { code: 'BIF', label: 'Burundi' },
//     { code: 'CVE', label: 'Cabo Verde' },
//     { code: 'KHR', label: 'Cambodia' },
//     { code: 'XAF', label: 'Cameroon' },
//     { code: 'CAD', label: 'Canada' },
//     { code: 'XAF', label: 'Central African Republic' },
//     { code: 'XAF', label: 'Chad' },
//     { code: 'CLP', label: 'Chile' },
//     { code: 'CNY', label: 'China' },
//     { code: 'COP', label: 'Colombia' },
//     { code: 'KMF', label: 'Comoros' },
//     { code: 'CDF', label: 'Congo' },
//     { code: 'CRC', label: 'Costa Rica' },
//     { code: 'HRK', label: 'Croatia' },
//     { code: 'CUP', label: 'Cuba' },
//     { code: 'EUR', label: 'Cyprus' },
//     { code: 'CZK', label: 'Czech Republic' },
//     { code: 'DKK', label: 'Denmark' },
//     { code: 'DJF', label: 'Djibouti' },
//     { code: 'XCD', label: 'Dominica' },
//     { code: 'DOP', label: 'Dominican Republic' },
//     { code: 'USD', label: 'Ecuador' },
//     { code: 'EGP', label: 'Egypt' },
//     { code: 'USD', label: 'El Salvador' },
//     { code: 'XAF', label: 'Equatorial Guinea' },
//     { code: 'ERN', label: 'Eritrea' },
//     { code: 'EUR', label: 'Estonia' },
//     { code: 'SZL', label: 'Eswatini' },
//     { code: 'ETB', label: 'Ethiopia' },
//     { code: 'FJD', label: 'Fiji' },
//     { code: 'EUR', label: 'Finland' },
//     { code: 'EUR', label: 'France' },
//     { code: 'XAF', label: 'Gabon' },
//     { code: 'GMD', label: 'Gambia' },
//     { code: 'GEL', label: 'Georgia' },
//     { code: 'EUR', label: 'Germany' },
//     { code: 'GHS', label: 'Ghana' },
//     { code: 'EUR', label: 'Greece' },
//     { code: 'XCD', label: 'Grenada' },
//     { code: 'GTQ', label: 'Guatemala' },
//     { code: 'GNF', label: 'Guinea' },
//     { code: 'XOF', label: 'Guinea-Bissau' },
//     { code: 'GYD', label: 'Guyana' },
//     { code: 'HTG', label: 'Haiti' },
//     { code: 'HNL', label: 'Honduras' },
//     { code: 'HUF', label: 'Hungary' },
//     { code: 'ISK', label: 'Iceland' },
//     { code: 'INR', label: 'India' },
//     { code: 'IDR', label: 'Indonesia' },
//     { code: 'IRR', label: 'Iran' },
//     { code: 'IQD', label: 'Iraq' },
//     { code: 'EUR', label: 'Ireland' },
//     { code: 'ILS', label: 'Israel' },
//     { code: 'EUR', label: 'Italy' },
//     { code: 'JMD', label: 'Jamaica' },
//     { code: 'JPY', label: 'Japan' },
//     { code: 'JOD', label: 'Jordan' },
//     { code: 'KZT', label: 'Kazakhstan' },
//     { code: 'KES', label: 'Kenya' },
//     { code: 'AUD', label: 'Kiribati' },
//     { code: 'KWD', label: 'Kuwait' },
//     { code: 'KGS', label: 'Kyrgyzstan' },
//     { code: 'LAK', label: 'Laos' },
//     { code: 'EUR', label: 'Latvia' },
//     { code: 'LBP', label: 'Lebanon' },
//     { code: 'LSL', label: 'Lesotho' },
//     { code: 'LRD', label: 'Liberia' },
//     { code: 'LYD', label: 'Libya' },
//     { code: 'CHF', label: 'Liechtenstein' },
//     { code: 'EUR', label: 'Lithuania' },
//     { code: 'EUR', label: 'Luxembourg' },
//     { code: 'MGA', label: 'Madagascar' },
//     { code: 'MWK', label: 'Malawi' },
//     { code: 'MYR', label: 'Malaysia' },
//     { code: 'MVR', label: 'Maldives' },
//     { code: 'XOF', label: 'Mali' },
//     { code: 'EUR', label: 'Malta' },
//     { code: 'USD', label: 'Marshall Islands' },
//     { code: 'MRU', label: 'Mauritania' },
//     { code: 'MUR', label: 'Mauritius' },
//     { code: 'MXN', label: 'Mexico' },
//     { code: 'USD', label: 'Micronesia' },
//     { code: 'MDL', label: 'Moldova' },
//     { code: 'EUR', label: 'Monaco' },
//     { code: 'MNT', label: 'Mongolia' },
//     { code: 'EUR', label: 'Montenegro' },
//     { code: 'MAD', label: 'Morocco' },
//     { code: 'MZN', label: 'Mozambique' },
//     { code: 'MMK', label: 'Myanmar' },
//     { code: 'NAD', label: 'Namibia' },
//     { code: 'AUD', label: 'Nauru' },
//     { code: 'NPR', label: 'Nepal' },
//     { code: 'EUR', label: 'Netherlands' },
//     { code: 'NZD', label: 'New Zealand' },
//     { code: 'NIO', label: 'Nicaragua' },
//     { code: 'XOF', label: 'Niger' },
//     { code: 'NGN', label: 'Nigeria' },
//     { code: 'KPW', label: 'North Korea' },
//     { code: 'MKD', label: 'North Macedonia' },
//     { code: 'NOK', label: 'Norway' },
//     { code: 'OMR', label: 'Oman' },
//     { code: 'PKR', label: 'Pakistan' },
//     { code: 'USD', label: 'Palau' },
//     { code: 'PAB', label: 'Panama' },
//     { code: 'PGK', label: 'Papua New Guinea' },
//     { code: 'PYG', label: 'Paraguay' },
//     { code: 'PEN', label: 'Peru' },
//     { code: 'PHP', label: 'Philippines' },
//     { code: 'PLN', label: 'Poland' },
//     { code: 'EUR', label: 'Portugal' },
//     { code: 'QAR', label: 'Qatar' },
//     { code: 'RON', label: 'Romania' },
//     { code: 'RUB', label: 'Russia' },
//     { code: 'RWF', label: 'Rwanda' },
//     { code: 'XCD', label: 'Saint Kitts and Nevis' },
//     { code: 'XCD', label: 'Saint Lucia' },
//     { code: 'XCD', label: 'Saint Vincent and the Grenadines' },
//     { code: 'WST', label: 'Samoa' },
//     { code: 'EUR', label: 'San Marino' },
//     { code: 'STN', label: 'Sao Tome and Principe' },
//     { code: 'SAR', label: 'Saudi Arabia' },
//     { code: 'XOF', label: 'Senegal' },
//     { code: 'RSD', label: 'Serbia' },
//     { code: 'SCR', label: 'Seychelles' },
//     { code: 'SLL', label: 'Sierra Leone' },
//     { code: 'SGD', label: 'Singapore' },
//     { code: 'EUR', label: 'Slovakia' },
//     { code: 'EUR', label: 'Slovenia' },
//     { code: 'SBD', label: 'Solomon Islands' },
//     { code: 'SOS', label: 'Somalia' },
//     { code: 'ZAR', label: 'South Africa' },
//     { code: 'KRW', label: 'South Korea' },
//     { code: 'SSP', label: 'South Sudan' },
//     { code: 'EUR', label: 'Spain' },
//     { code: 'LKR', label: 'Sri Lanka' },
//     { code: 'SDG', label: 'Sudan' },
//     { code: 'SRD', label: 'Suriname' },
//     { code: 'SEK', label: 'Sweden' },
//     { code: 'CHF', label: 'Switzerland' },
//     { code: 'SYP', label: 'Syria' },
//     { code: 'TWD', label: 'Taiwan' },
//     { code: 'TJS', label: 'Tajikistan' },
//     { code: 'TZS', label: 'Tanzania' },
//     { code: 'THB', label: 'Thailand' },
//     { code: 'XOF', label: 'Togo' },
//     { code: 'TOP', label: 'Tonga' },
//     { code: 'TTD', label: 'Trinidad and Tobago' },
//     { code: 'TND', label: 'Tunisia' },
//     { code: 'TRY', label: 'Turkey' },
//     { code: 'TMT', label: 'Turkmenistan' },
//     { code: 'AUD', label: 'Tuvalu' },
//     { code: 'UGX', label: 'Uganda' },
//     { code: 'UAH', label: 'Ukraine' },
//     { code: 'AED', label: 'United Arab Emirates' },
//     { code: 'GBP', label: 'United Kingdom' },
//     { code: 'USD', label: 'United States' },
//     { code: 'UYU', label: 'Uruguay' },
//     { code: 'UZS', label: 'Uzbekistan' },
//     { code: 'VUV', label: 'Vanuatu' },
//     { code: 'VES', label: 'Venezuela' },
//     { code: 'VND', label: 'Vietnam' },
//     { code: 'YER', label: 'Yemen' },
//     { code: 'ZMW', label: 'Zambia' },
//     { code: 'ZWL', label: 'Zimbabwe' }
//   ];
  