apiVersion: v1
kind: Secret
metadata:
  name: lms-secrets
  namespace: lms-system
type: Opaque
data:
  # You'll need to replace these with your actual base64 encoded values
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9hbm5hbnRkNjQ6cjhuQXlCVVRxZTZFUzFZakBjb2Ryb2lkaHViLmxveWJuZnUubW9uZ29kYi5uZXQ=
  JWT_SECRET: bmhtMWtHRkp1dVBMQmxfMWZJcjZfblc0ZkJsdmRhajBoOEd1NDJPb0E5M2tXWEFmWEdkdThHS3A3LXlCX0VMRQ==