version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development