version: "3.8"

services:
    # PHP Service
    laravel_eleven_app:
        build:
            args:
                user: sagun
                uid: 1003
                gid: 1003
            context: ./
            dockerfile: Dockerfile
        image: laravel_eleven_app_image
        container_name: laravel_eleven_app
        restart: unless-stopped
        depends_on:
            laravel_eleven_app_mysql:
                condition: service_healthy
        working_dir: /var/www
        volumes:
            - ./:/var/www:delegated
            - laravel_eleven_storage:/var/www/storage
        networks:
            - laravel_eleven_app_network
        healthcheck:
            test: ["CMD", "php-fpm", "-t"]
            interval: 30s
            timeout: 10s
            retries: 3
        environment:
            PHP_MEMORY_LIMIT: "256M"
            PHP_MAX_EXECUTION_TIME: "60"

    # Nginx service
    laravel_eleven_webserver:
        image: nginx:1.25-alpine
        container_name: laravel_eleven_webserver_container
        restart: unless-stopped
        ports:
            - "127.0.0.1:6162:80"
        depends_on:
            - laravel_eleven_app
        volumes:
            - ./:/var/www:ro
            - ./docker-compose/nginx/:/etc/nginx/conf.d:ro
            - laravel_eleven_storage:/var/www/storage
        networks:
            - laravel_eleven_app_network
        healthcheck:
            test: ["CMD", "nginx", "-t"]
            interval: 30s
            timeout: 10s
            retries: 3

    # MySQL service
    laravel_eleven_app_mysql:
        image: mysql:8.0
        container_name: laravel_eleven_app_mysql
        restart: unless-stopped
        ports:
            - "127.0.0.1:3337:3306"
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MYSQL_DATABASE: laravel_eleven_app
            MYSQL_USER: laravel_eleven_user
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
        volumes:
            - laravel_eleven_mysql_data:/var/lib/mysql
            - ./docker-compose/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
        networks:
            - laravel_eleven_app_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 3
        secrets:
            - db_root_password
            - db_password

    # phpMyAdmin service
    laravel_eleven_phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        container_name: laravel_eleven_phpmyadmin_container
        restart: unless-stopped
        ports:
            - "127.0.0.1:8383:80"
        environment:
            PMA_HOST: laravel_eleven_app_mysql
            PMA_PORT: 3306
            PMA_USER_FILE: /run/secrets/pma_user
            PMA_PASSWORD_FILE: /run/secrets/pma_password
            UPLOAD_LIMIT: 64M
        depends_on:
            laravel_eleven_app_mysql:
                condition: service_healthy
        networks:
            - laravel_eleven_app_network
        secrets:
            - pma_user
            - pma_password

    # Redis service
    laravel_eleven_redis:
        image: redis:7.2-alpine
        container_name: laravel_eleven_redis_container
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "127.0.0.1:7379:6379"
        networks:
            - laravel_eleven_app_network
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    laravel_eleven_mysql_data:
        driver: local
    laravel_eleven_storage:
        driver: local
    redis_data:
        driver: local

networks:
    laravel_eleven_app_network:
        driver: bridge
        name: laravel_eleven_network
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16

secrets:
    db_root_password:
        file: ./secrets/db_root_password.txt
    db_password:
        file: ./secrets/db_password.txt
    pma_user:
        file: ./secrets/pma_user.txt
    pma_password:
        file: ./secrets/pma_password.txt
